# Site settings
title: nicosp
description: > # this means to ignore newlines until "baseurl:"
  short tutorials and stuff
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://nicosp.github.io" # the base hostname & protocol for your site

email: nicosp@gmail.com
#twitter_username: NicosPanayides
github_username: nicosp

# Build settings
markdown: kramdown
