# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: n0auth.com
email: webmaster@n0auth.com
description: > # this means to ignore newlines until "baseurl:"
  short tutorials and stuff
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://n0auth.com" # the base hostname & protocol for your site
#twitter_username: NicosPanayides
#github_username:  jekyll

# Build settings
markdown: kramdown
