# Site settings
title: n0auth.com
description: > # this means to ignore newlines until "baseurl:"
  short tutorials and stuff
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://n0auth.com" # the base hostname & protocol for your site

email: webmaster@n0auth.com
#twitter_username: NicosPanayides
#github_username:  jekyll

# Build settings
markdown: kramdown
